"""17 - Mini semantic-search example

Uses small hand-crafted vectors only to demonstrate the ranking logic.
These vectors are illustrative and are NOT generated by an embedding model.
"""

import math

def cosine_similarity(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


query = [0.9, 0.1, 0.2]

documents = {
    "Python data analysis": [0.8, 0.2, 0.1],
    "Deep learning basics": [0.2, 0.8, 0.3],
    "Pandas DataFrame guide": [0.85, 0.15, 0.2],
    "Travel photography": [0.1, 0.1, 0.9],
}

results = []
for name, vector in documents.items():
    score = cosine_similarity(query, vector)
    results.append((name, score))

results.sort(key=lambda item: item[1], reverse=True)

print("Query vector:", query)
print("\nRanked results:")
for rank, (name, score) in enumerate(results, 1):
    print(f"{rank}. {name} -> {score:.4f}")

print("\nNext step: replace illustrative vectors with real embedding-model outputs.")
